TicketsApplication/src/TicketsApplication/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BLL.Interfaces;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using TicketsApplication.Models;
using BLL.DTO;
using Microsoft.AspNetCore.Authorization;

namespace TicketsApplication.Controllers
{
    [Authorize]
    public class TicketController : Controller
    {
        ITicketService ts;

        public TicketController(ITicketService ts)
        {
            this.ts = ts;
        }

        private void UserTitle()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                HttpContext.Session.SetString("User", HttpContext.User.Identity.Name);
                ViewBag.Message = HttpContext.Session.GetString("User");
            }
            else
            {
                ViewBag.Message = "Guest";
            }
        }

        [AllowAnonymous]
        public IActionResult Tickets(int id)
        {
            UserTitle();
            TicketCountVM tcvm = new TicketCountVM();
            tcvm.PriceAndCount = Mapper.Map<ICollection<KeyValuePair<decimal, int>>>(ts.GetTicketCountDTO(id));
            EventDTO ev = ts.GetEventForTicket(id);
            tcvm.Event = Mapper.Map<EventVM>(ev);
            return View(tcvm);
        }

        public IActionResult TicketsForOrder(decimal price, int eventId)
        {
            UserTitle();
            List<TicketDTO> tdto = ts.TicketsForEvent(eventId, price);
            List<TicketVM> tickets = Mapper.Map<List<TicketVM>>(tdto);
            return View(tickets);
        }

        public IActionResult UserTickets(string nick)
        {
            UserTitle();
            List<TicketVM> tickets = Mapper.Map<List<TicketVM>>(ts.TicketsForUser(nick));
            return View(tickets);
        }
        public IActionResult Buy(List<TicketVM> models)
        {
            return View();
        }
    }
}

TicketsApplication/src/TicketsApplication/Views/Ticket/Buy.cshtml
кукук

TicketsApplication/src/TicketsApplication/Views/Ticket/Tickets.cshtml
@model TicketsApplication.Models.TicketCountVM
@{
    Layout = null;
}
<!doctype html>
<html>
<head>
    <title>Tickets Resailing</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body>
    <header>
        <input type="text" name="user" class="user" value="@ViewBag.Message" />
        @if (User.Identity.IsAuthenticated)
        {
            @Html.ActionLink("Logout", "Logout", "Account")
        }
        else
        {
            @Html.ActionLink("LogIn", "Login", "Account")
            @Html.ActionLink("Register", "Register", "Account")
        }
    </header>

    <h3>@Model.Event.Name</h3>
    <p>@Model.Event.City, @Model.Event.Venue</p>
    <p>@Model.Event.Date.ToString("dd.MM")</p>
    <p>@Model.Event.Description</p>

    <h2>Ticket Information:</h2>

    @foreach (var i in Model.PriceAndCount)
    {
        <div class="event">
            <p>Cost:  @i.Key</p>
            <p>Count:  @i.Value</p>
            @using (Html.BeginForm("TicketsForOrder", "Ticket", FormMethod.Post))
            {

                @Html.Hidden("price", @i.Key)
                @Html.Hidden("eventId", Model.Event.ID)

                <input type="submit" value="Order" />
            }
            <hr />
        </div>

    }

</body>
</html>

TicketsApplication/src/TicketsApplication/Views/Ticket/TicketsForOrder.cshtml
@model List<TicketsApplication.Models.TicketVM>
@{
    Layout = null;
}
<!doctype html>
<html>
<head>
    <title>Tickets Resailing</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body>
    <header>
        <input type="text" name="user" class="user" value="@ViewBag.Message" />
        @Html.ActionLink("LogIn", "Login", "Account")
        @Html.ActionLink("Register", "Register", "Account")
    </header>
    <h2>Tickets:</h2>

    @using (Html.BeginForm("Buy", "Ticket", FormMethod.Post))
    {
        var mbox = (List<TicketsApplication.Models.TicketVM>)Model;

        for (int i = 0; i < mbox.Count; i++)
        {
            <div class="event">
                <p>Cost: @Model[i].Price, Seller: @Model[i].Seller</p>
                @Html.CheckBox("[" + @i + "].ForSale", Model[i].ForSale)
                @Html.Hidden("[" + @i + "].Price", @Model[i].Price)
                @Html.Hidden("[" + @i + "].SellerID", @Model[i].SellerID)
                @Html.Hidden("[" + @i + "].EventID", @Model[i].EventID)
                @Html.Hidden("[" + @i + "].Seller", @Model[i].Seller)
                @Html.Hidden("[" + @i + "].Price", @Model[i].Price)
                @Html.Hidden("[" + @i + "].Availability", @Model[i].Availability)
            </div>
        }

        <div>
            <input type="submit" value="Buy" />
        </div>
    }

</body>
</html>

TicketsApplication/src/TicketsApplication/Views/Ticket/UserTickets.cshtml
@model List<TicketsApplication.Models.TicketVM>
@{
    Layout = null;
}
<!doctype html>
<html>

<head>
    <title>Tickets Resailing</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body>
    <header>
        <input type="text" name="user" class="user" value="@ViewBag.Message" />
            @Html.ActionLink("Logout", "Logout", "Account")
            @Html.RouteLink("My Tickets", new { Controller = "Ticket", Action = "UserTickets", nick = User.Identity.Name })

    </header>

    @foreach (var i in Model)
    {
        <div class="event">
            <p>@i.Price</p>
            <div class="blackLink">@Html.RouteLink(@i.Seller, new { Controller = "User", Action = "UserInformation", nick = @i.Seller })</div>
            <p>@i.Event</p>
        </div>

    }

</body>
</html>